parameters:
- name: toscaTests
  displayName: Tosca Tests
  #type: object
  #default: 3a12f411-64ba-5773-e489-87334879e9f8
trigger:
- main
- release

pool:
  vmImage: 'NonProdWindows' # Use existing windows agent machine

stages:
- stage: TOSCAExecution
  displayName: 'Execute TOSCA Script'
  jobs:
  - job: Execute_Tosca_Test
    displayName: 'Execute Tosca Test Suite'
    steps:
    - checkout: self
    - script: |
    #     # Clone the repository containing configXML
    # git clone <https://github.com/AzurePipelineIntegration/Demo3>
    #     # Run Tosca test suite
    # "C:\Path\To\TOSCA\executable" "C:\Path\To\TOSCA\script.tosca" -config "\Path\To\config.xml"
    #     # Replace <path_to_tosca_executable> and <path_to_configXML> with actual paths
      
      displayName: 'Execute TOSCA Script'


    PathtoPublish: '$(Common.TestResultsDirectory)\ToscaCI.xml'
    ArtifactName: 'JUnit_Reports'
    publishLocation: 'Container'
  condition: succeededOrFailed() has context menu
